import * as React from "react";
import { createContext, useContext, useState } from "react";

export type Language = "TH" | "EN" | "CN";

interface LanguageProviderProps {
  children: React.ReactNode;
  defaultLanguage?: Language;
}

interface LanguageProviderState {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  TH: {
    about: "เกี่ยวกับเรา",
    projects: "โปรเจกต์",
    experience: "ประสบการณ์",
    works: "ผลงาน",
    contact: "ติดต่อ",
    logo: "THANAKIT",
    banner_hi: "ธนกฤต สุวรรณศรี",
    banner_role: "กราฟิกดีไซน์เนอร์ และ นักพัฒนาเว็บไซต์",
    banner_desc: "สร้างสรรค์ผลงานด้วยความประณีตและเทคโนโลยีที่ทันสมัย",
    banner_highlight_title: "ความเชี่ยวชาญ",
    banner_highlight_desc: "เชี่ยวชาญการใช้โปรแกรมตระกูล Adobe และเครื่องมือออกแบบระดับมืออาชีพ",
    banner_cta_title: "ผลงานล่าสุด",
    banner_cta_desc: "รับชมโปรเจกต์ที่ผมได้ตั้งใจสร้างสรรค์ขึ้นมา",
    banner_view_projects: "ดูผลงานทั้งหมด",
    about_title: "เกี่ยวกับฉัน",
    about_desc: "จากที่ผมเรียนสถาปัตย์ ผมเริ่มต้นจากการได้เรียนรู้สิ่งรอบตัว และได้ศึกษาอาคารต่อที่ประเทศไต้หวัน จึงเห็นการออกแบบอาคาร รูปแบบอาคาร และประเภทของอาคารจึงนำแนวคิดในส่วนนี้มาปรับใช้ในประเทศไทย เส้นทางจากการศึกษาแนวคิด พฤติกรรม อัตลักษณ์ นำมาผสมผสานเข้ากับสถาปัตยกรรม และได้ศึกษางานต่อที่ประเทศไทย ในด้าน Content Creator, Graphic Design ผมเชื่อว่างานออกแบบที่ดีคือการผสมผสานความเข้าใจระหว่างความหลงใหลในด้านเฉพาะทางและความสวยงามที่เข้ากันอย่างลงตัว",
    about_exp_years: "1+",
    about_exp_label: "ปีที่ทำงาน",
    about_projects_count: "3+",
    about_projects_label: "โปรเจกต์ที่สำเร็จ",
    internship_title: "ฝึกงาน",
    internship_company: "ORIGIN PROPERTY PUBLIC CO.,LTD",
    internship_date: "มิถุนายน 2022 - สิงหาคม 2022",
    internship_role: "ผู้ช่วยนักออกแบบสถาปัตยกรรม (ฝึกงาน)",
    internship_desc: "ช่วยงานด้านการออกแบบสถาปัตยกรรมเบื้องต้น การทำโมเดล 3 มิติ และการจัดทำเอกสารนำเสนอโครงการ",
    internship_highlights: "จุดเด่นที่ได้รับ",
    internship_h1: "จัดทำโมเดล 3 มิติมากกว่า 5 โครงการ",
    internship_h2: "เรียนรู้กระบวนการทำงานจริงในหน้างาน",
    internship_h3: "พัฒนาทักษะการใช้โปรแกรม SketchUp และ AutoCAD",
    education_title: "ประวัติการศึกษา",
    education_degree: "คณะสถาปัตยกรรมศาสตร์ (สถ.32)",
    education_university: "มหาวิทยาลัยรังสิต",
    education_date: "2018 - 2023",
    education_desc: "เน้นการออกแบบสถาปัตยกรรมที่คำนึงถึงบริบท สภาพแวดล้อม และการใช้งานของผู้ใช้เป็นหลัก",
    projects_title: "โปรเจกต์ที่น่าสนใจ",
    projects_view_all: "ดูทั้งหมด",
    project_1_title: "THAILAND EXHIBITION",
    project_1_desc: "การทำงานร่วมกับทีม POKERTALK TEAM THAILAND,ASIA เป็นการ่วมงานกับทีมระหว่างประเทศ",
    project_2_title: "ENTERTAINMENT COMPLEX POQUE",
    project_2_desc: "การออกแบบอาคารสำหรับการแข่งขันกีฬาโป๊กเกอร์ในประเทศไทย",
    project_3_title: "ORIGIN",
    project_3_desc: "การฝึกงานสหกิจศึกษาที่บริษัท ORIGIN",
    projects_page_back: "กลับหน้าหลัก",
    projects_page_title: "โปรเจกต์ทั้งหมด",
    projects_page_desc: "รวบรวมโปรเจกต์การออกแบบสถาปัตยกรรม กราฟิกดีไซน์ และการสร้างสรรค์คอนเทนต์ทั้งหมดของผม",
    projects_filter_all: "ทั้งหมด",
    projects_filter_arch: "สถาปัตยกรรม",
    projects_filter_design: "กราฟิกดีไซน์",
    projects_filter_content: "คอนเทนต์",
    projects_search_placeholder: "ค้นหาโปรเจกต์หรือเครื่องมือ...",
    projects_no_results: "ไม่พบโปรเจกต์ที่ค้นหา",
    projects_no_results_desc: "ลองปรับการกรองหรือคำค้นหาของคุณใหม่อีกครั้ง",
    project_detail_client: "ลูกค้า",
    project_detail_year: "ปีที่ทำ",
    project_detail_category: "หมวดหมู่",
    project_detail_tools: "เครื่องมือที่ใช้",
    project_detail_back: "กลับ",
    project_detail_visit: "เยี่ยมชมเว็บไซต์",
    project_detail_gallery: "แกลเลอรีผลงาน",
    project_1_full_desc: "การทำงานร่วมกับทีม POKERTALK TEAM THAILAND,ASIA เป็นการร่วมงานกับทีมระหว่างประเทศที่เน้นการผลิตคอนเทนต์และการจัดการสื่อดิจิทัลระดับภูมิภาค",
    project_2_full_desc: "การออกแบบอาคารสำหรับการแข่งขันกีฬาโป๊กเกอร์ในประเทศไทยที่เน้นการสร้างพื้นที่สันทนาการที่ทันสมัยและตอบโจทย์การใช้งานเฉพาะทาง",
    project_3_full_desc: "การฝึกงานสหกิจศึกษาที่บริษัท ORIGIN ซึ่งได้เรียนรู้กระบวนการทำงานจริงในสายงานสถาปัตยกรรมและการออกแบบ",
    exp_title: "ประสบการณ์การทำงาน",
    exp_freelance_title: "POKERTALKTH",
    exp_freelance_role: "Content Creator",
    exp_freelance_date: "ตุลาคม 2025 - ธันวาคม 2026",
    exp_freelance_desc: "รับผิดชอบการสร้างสรรค์คอนเทนต์ดิจิทัล การออกแบบสื่อประชาสัมพันธ์ และการจัดการโซเชียลมีเดีย",
    exp_freelance_h1: "จัดการโพสต์สื่อโซเชียลมีเดียสูงสุด 20 โพสต์ต่อวัน",
    exp_freelance_h2: "เรียนรู้กระบวนการทำงานจริงหน้างาน",
    exp_freelance_h3: "พัฒนาทักษะการใช้โปรแกรม Adobe และ Social Media",
    works_title: "ผลงาน",
    works_view_all: "ดูทั้งหมด",
    works_view_more: "ดูเพิ่มเติม",
    works_filter_all: "ทั้งหมด",
    works_filter_ui: "Design",
    works_filter_web: "Vdo",
    works_filter_mobile: "Marketing",
    works_page_title: "ผลงานทั้งหมด",
    works_page_desc: "รวบรวมผลงานด้านการออกแบบ กราฟิกดีไซน์ วิดีโอ และการตลาดทั้งหมดของผม",
    works_info_title: "ข้อมูลผลงาน",
    work_1_desc: "การทำงานร่วมกับทีม POKERTALK TEAM THAILAND, ASIA เป็นการร่วมงานกับทีมระหว่างประเทศที่เน้นการผลิตคอนเทนต์และการจัดการสื่อดิจิทัลระดับภูมิภาค - การวางแผนตารางงานสตอรี่บอร์ด",
    work_2_desc: "คิดบทสัมภาษณ์ และบรีฟผู้เข้าร่วมวิดีโอรวมถึงบรีฟทีมกล้อง",
    work_3_desc: "อัตราการมีส่วนร่วมของโพสต์ยอดนิยม",
    work_4_desc: "VDO editor ตัดต่อ motion",
    work_5_desc: "เว็บไซต์พอร์ตโฟลิโอที่เน้นความลื่นไหลและอนิเมชั่นที่สวยงาม",
    work_6_desc: "การฝึกงานสหกิจศึกษาที่บริษัท ORIGIN ซึ่งได้เรียนรู้กระบวนการทำงานจริงในสายงานสถาปัตยกรรมและการออกแบบ",
    work_6_key_section: "คีย์ข้อมูลห้อง",
    work_7_desc: "การทำงานร่วมกับทีม POKERTALK TEAM THAILAND, ASIA เป็นการร่วมงานกับทีมระหว่างประเทศที่เน้นการผลิตคอนเทนต์และการจัดการสื่อดิจิทัลระดับภูมิภาค",
    work_section_arch: "ARCHITECTURE",
    work_section_key: "KEY ข้อมูล",
    work_section_interview: "INTERVIEW",
    work_section_interview_desc: "การคิดบทสัมภาษณ์ บรีฟผู้เข้าร่วม และการจัดการทีมกล้องเพื่อสร้างคอนเทนต์คุณภาพ",
    work_section_ps_ai: "PHOTOSHOP & ILLUSTRATOR",
    work_section_ps_ai_desc: "งานออกแบบกราฟิก ตกแต่งภาพ และสร้าง Visual Assets สำหรับโซเชียลมีเดีย",
    work_section_content: "CONTENT CREATOR",
    work_section_content_desc: "Storyboard Schedule Planning - การวางแผนตารางงานและลำดับภาพในการผลิต",
    work_section_report: "REPORT",
    work_section_report_desc: "Popular Post Engagement Rate - การทำรายงานสรุปผลการตอบรับและสถิติหลังบ้าน",
    work_section_law: "LAW",
    work_section_law_desc: "Architecture ENTERTAINMENT COMPLEX POQUE",
    work_section_meme: "MEME",
    work_section_news: "NEWS",
    work_section_tips: "TIPS",
    work_section_scale: "SCALE",
    work_view_more: "ดูรายละเอียดเพิ่มเติม",
    work_video_title: "วิดีโออ้างอิง",
    work_video_desc: "รับชมผลงานวิดีโอและบรรยากาศการสัมภาษณ์ผ่าน Google Drive",
    work_video_button: "ดูวิดีโอ",
    contact_title_1: "LET'S DO IT",
    contact_title_2: "TO FUTURE",
    contact_desc: "ผมมีความเชื่อที่อยากจะเห็นคนไทยมีสถานที่ฝึกซ้อมที่รองรับคนไทย รวมทั้งมีนักออกแบบจากในประเทศโดยเฉพาะทาง",
    contact_details_label: "ข้อมูลการติดต่อ",
    contact_location: "กรุงเทพมหานคร, ประเทศไทย",
    contact_status_label: "สถานะปัจจุบัน",
    contact_status_value: "พร้อมรับงาน Freelance & Full-time",
  },
  EN: {
    about: "About",
    projects: "Projects",
    experience: "Experience",
    works: "Works",
    contact: "Contact",
    logo: "THANAKIT",
    banner_hi: "Hi, I'm Thanakit",
    banner_role: "Graphic Designer & Web Developer",
    banner_desc: "Crafting digital experiences with precision and modern technology.",
    banner_highlight_title: "My Expertise",
    banner_highlight_desc: "Specializing in Adobe Creative Suite and professional design tools.",
    banner_cta_title: "Featured Projects",
    banner_cta_desc: "Explore the projects I've built with passion and dedication.",
    banner_view_projects: "View All Projects",
    about_title: "About Me",
    about_desc: "Starting from my background in Architecture, I began by learning from my surroundings and continued my architectural studies in Taiwan. This experience allowed me to observe diverse building designs, styles, and types, which I then adapted to the Thai context. My journey involves integrating concepts of behavior and identity into architecture. I furthered my studies in Thailand in the fields of Content Creation and Graphic Design. I believe that great design is a seamless blend of specialized passion and perfectly matched aesthetics.",
    about_exp_years: "1+",
    about_exp_label: "Years Experience",
    about_projects_count: "3+",
    about_projects_label: "Projects Completed",
    internship_title: "Internship",
    internship_company: "ORIGIN PROPERTY PUBLIC CO.,LTD",
    internship_date: "June 2022 - August 2022",
    internship_role: "Architectural Design Intern",
    internship_desc: "Assisted in preliminary architectural design, 3D modeling, and preparing project presentation documents.",
    internship_highlights: "Key Highlights",
    internship_h1: "Developed 5+ 3D models for residential projects",
    internship_h2: "Learned real-world site inspection processes",
    internship_h3: "Improved SketchUp and AutoCAD proficiency",
    education_title: "Education",
    education_degree: "Faculty of Architecture (Arch.32)",
    education_university: "Rangsit University",
    education_date: "2018 - 2023",
    education_desc: "Focusing on architectural design that considers context, environment, and user functionality as the core.",
    projects_title: "Featured Projects",
    projects_view_all: "View All",
    project_1_title: "THAILAND EXHIBITION",
    project_1_desc: "Collaborating with POKERTALK TEAM THAILAND, ASIA in an international team environment.",
    project_2_title: "ENTERTAINMENT COMPLEX POQUE",
    project_2_desc: "Architectural design for poker sports competitions in Thailand.",
    project_3_title: "ORIGIN",
    project_3_desc: "Cooperative education internship.",
    projects_page_back: "Back to Home",
    projects_page_title: "All Projects",
    projects_page_desc: "A comprehensive collection of my projects across architecture, graphic design, and content creation.",
    projects_filter_all: "All",
    projects_filter_arch: "Architecture",
    projects_filter_design: "Design",
    projects_filter_content: "Content",
    projects_search_placeholder: "Search projects or tools...",
    projects_no_results: "No projects found",
    projects_no_results_desc: "Try adjusting your filters or search query.",
    project_detail_client: "Client",
    project_detail_year: "Year",
    project_detail_category: "Category",
    project_detail_tools: "Tools Used",
    project_detail_back: "Back",
    project_detail_visit: "Visit Website",
    project_detail_gallery: "Project Gallery",
    project_1_full_desc: "Collaborating with POKERTALK TEAM THAILAND, ASIA in an international team environment, focusing on regional digital content production and media management.",
    project_2_full_desc: "Architectural design for poker sports competitions in Thailand, focusing on creating modern and specialized recreational spaces.",
    project_3_full_desc: "Cooperative education internship at ORIGIN, gaining real-world experience in architecture and design workflows.",
    exp_title: "Work Experience",
    exp_freelance_title: "POKERTALKTH",
    exp_freelance_role: "Content Creator",
    exp_freelance_date: "October 2025 - December 2026",
    exp_freelance_desc: "Responsible for digital content creation, promotional media design, and social media management.",
    exp_freelance_h1: "Managed up to 20 social media posts per day",
    exp_freelance_h2: "Learned real-world on-site work processes",
    exp_freelance_h3: "Developed skills in Adobe Creative Suite and social media management",
    works_title: "Works",
    works_view_all: "View All",
    works_view_more: "View More",
    works_filter_all: "All",
    works_filter_ui: "Design",
    works_filter_web: "Vdo",
    works_filter_mobile: "Marketing",
    works_page_title: "All Works",
    works_page_desc: "A comprehensive collection of my graphic designs, videos, and marketing works.",
    works_info_title: "Work Information",
    work_1_desc: "Collaborating with POKERTALK TEAM THAILAND, ASIA in an international team environment focusing on regional digital content production - Storyboard schedule planning",
    work_2_desc: "Interview planning and briefing participants and camera crew",
    work_3_desc: "Popular post engagement rate",
    work_4_desc: "VDO editor and motion graphics.",
    work_5_desc: "Portfolio website focusing on fluidity and beautiful animations.",
    work_6_desc: "Cooperative education internship at ORIGIN, gaining real-world experience in architecture and design workflows.",
    work_6_key_section: "Room Data Entry",
    work_7_desc: "Collaborating with POKERTALK TEAM THAILAND, ASIA. Working with an international team focused on content production and regional digital media management.",
    work_section_arch: "ARCHITECTURE",
    work_section_key: "KEY INFO",
    work_section_interview: "INTERVIEW",
    work_section_interview_desc: "Interview planning, participant briefing, and camera crew management for high-quality content.",
    work_section_ps_ai: "PHOTOSHOP & ILLUSTRATOR",
    work_section_ps_ai_desc: "Graphic design, image editing, and visual asset creation for social media.",
    work_section_content: "CONTENT CREATOR",
    work_section_content_desc: "Storyboard Schedule Planning - Strategic planning for production flow and timing.",
    work_section_report: "REPORT",
    work_section_report_desc: "Popular Post Engagement Rate - Comprehensive reporting on reach and engagement statistics.",
    work_section_law: "LAW",
    work_section_law_desc: "Architecture ENTERTAINMENT COMPLEX POQUE",
    work_section_meme: "MEME",
    work_section_news: "NEWS",
    work_section_tips: "TIPS",
    work_section_scale: "SCALE",
    work_view_more: "View More Details",
    work_video_title: "Reference Video",
    work_video_desc: "View the production result and interview session on Google Drive.",
    work_video_button: "WATCH VIDEO",
    contact_title_1: "LET'S DO IT",
    contact_title_2: "TO FUTURE",
    contact_desc: "I believe in seeing Thai people have training facilities that support them, designed by local specialists from within the country.",
    contact_details_label: "Contact Details",
    contact_location: "Bangkok, Thailand",
    contact_status_label: "Current Status",
    contact_status_value: "Available for freelance & full-time",
  },
  CN: {
    about: "关于",
    projects: "项目",
    experience: "经验",
    works: "作品",
    contact: "联系",
    logo: "THANAKIT",
    banner_hi: "你好，我是 Thanakit",
    banner_role: "平面设计师 & 网页开发人员",
    banner_desc: "以精湛的工艺和现代技术打造数字体验。",
    banner_highlight_title: "我的专长",
    banner_highlight_desc: "擅长使用 Adobe 系列软件和专业设计工具。",
    banner_cta_title: "精选项目",
    banner_cta_desc: "探索我用心打造的项目。",
    banner_view_projects: "查看所有项目",
    about_title: "关于我",
    about_desc: "从建筑学背景出发，我开始从周围环境学习，并前往台湾继续深造建筑。这段经历让我观察到多样化的建筑设计、风格和类型，并将其应用到泰国的语境中。我的旅程是将行为和身份的概念融入建筑。随后，我在泰国进一步学习了内容创作和平面设计。我相信，优秀的设计是专业热情与完美契合的美学的无缝融合。",
    about_exp_years: "1+",
    about_exp_label: "年工作经验",
    about_projects_count: "3+",
    about_projects_label: "完成项目",
    internship_title: "实习经历",
    internship_company: "ORIGIN PROPERTY PUBLIC CO.,LTD",
    internship_date: "2022年6月 - 2022年8月",
    internship_role: "建筑设计实习生",
    internship_desc: "协助进行初步建筑设计、3D 建模和准备项目演示文档。",
    internship_highlights: "主要亮点",
    internship_h1: "为住宅项目开发了 5 个以上的 3D 模型",
    internship_h2: "学习了实际的现场检查流程",
    internship_h3: "提高了 SketchUp 和 AutoCAD 的熟练程度",
    education_title: "教育经历",
    education_degree: "建筑学院 (Arch.32)",
    education_university: "兰实大学",
    education_date: "2018 - 2023",
    education_desc: "专注于以环境、背景和用户功能为核心的建筑设计。",
    projects_title: "精选项目",
    projects_view_all: "查看全部",
    project_1_title: "THAILAND EXHIBITION",
    project_1_desc: "与 POKERTALK TEAM THAILAND, ASIA 团队在国际团队环境中合作。",
    project_2_title: "ENTERTAINMENT COMPLEX POQUE",
    project_2_desc: "泰国扑克体育比赛的建筑设计。",
    project_3_title: "ORIGIN",
    project_3_desc: "合作教育实习。",
    projects_page_back: "返回首页",
    projects_page_title: "所有项目",
    projects_page_desc: "我在建筑、平面设计和内容创作方面的完整项目集。",
    projects_filter_all: "全部",
    projects_filter_arch: "建筑设计",
    projects_filter_design: "平面设计",
    projects_filter_content: "内容创作",
    projects_search_placeholder: "搜索项目或工具...",
    projects_no_results: "未找到项目",
    projects_no_results_desc: "请尝试调整您的过滤器或搜索查询。",
    project_detail_client: "客户",
    project_detail_year: "年份",
    project_detail_category: "类别",
    project_detail_tools: "使用工具",
    project_detail_back: "返回",
    project_detail_visit: "访问网站",
    project_detail_gallery: "项目图库",
    project_1_full_desc: "与 POKERTALK TEAM THAILAND, ASIA 团队在国际团队环境中合作，专注于区域数字内容制作和媒体管理。",
    project_2_full_desc: "泰国扑克体育比赛的建筑设计，专注于创建现代和专业的休闲空间。",
    project_3_full_desc: "在 ORIGIN 公司的合作教育实习，获得建筑和设计工作流程的实际经验。",
    exp_title: "工作经验",
    exp_freelance_title: "POKERTALKTH",
    exp_freelance_role: "内容创作者",
    exp_freelance_date: "2025年10月 - 2026年12月",
    exp_freelance_desc: "负责数字内容创作、宣传媒体设计和社交媒体管理。",
    exp_freelance_h1: "每天管理多达 20 个社交媒体帖子",
    exp_freelance_h2: "学习了实际的现场工作流程",
    exp_freelance_h3: "培养了 Adobe 系列软件和社交媒体管理技能",
    works_title: "作品",
    works_view_all: "查看全部",
    works_view_more: "查看更多",
    works_filter_all: "全部",
    works_filter_ui: "Design",
    works_filter_web: "Vdo",
    works_filter_mobile: "Marketing",
    works_page_title: "所有作品",
    works_page_desc: "我的平面设计、视频和营销作品的完整集合。",
    works_info_title: "作品信息",
    work_1_desc: "与 POKERTALK TEAM THAILAND, ASIA 团队在国际团队环境中合作，专注于区域数字内容制作 - 分镜脚本进度规划",
    work_2_desc: "策划采访并向视频参与者和摄像团队进行简报",
    work_3_desc: "热门帖子互动率",
    work_4_desc: "视频编辑器和动态图形。",
    work_5_desc: "专注于流动性和优美动画的作品集网站。",
    work_6_desc: "在 ORIGIN 公司的合作教育实习，获得建筑和设计工作流程的实际经验。",
    work_6_key_section: "房间数据录入",
    work_7_desc: "与 POKERTALK TEAM THAILAND, ASIA 合作。与专注于内容制作和区域数字媒体管理的国际团队合作。",
    work_section_arch: "建筑设计",
    work_section_key: "关键信息",
    work_section_interview: "采访",
    work_section_ps_ai: "PHOTOSHOP & ILLUSTRATOR",
    work_section_content: "内容创作者",
    work_section_report: "报告",
    work_section_law: "法律",
    work_section_law_desc: "建筑娱乐综合体 POQUE",
    work_section_meme: "表情包",
    work_section_news: "新闻",
    work_section_tips: "小贴士",
    work_section_scale: "比例",
    work_view_more: "查看更多详情",
    contact_title_1: "让我们开始吧",
    contact_title_2: "面向未来",
    contact_desc: "我坚信泰国人民应该拥有由国内专业人士专门设计的培训场所。",
    contact_details_label: "联系详情",
    contact_location: "泰国曼谷",
    contact_status_label: "当前状态",
    contact_status_value: "可承接自由职业和全职工作",
  },
};

const LanguageContext = createContext<LanguageProviderState | undefined>(undefined);

export function LanguageProvider({
  children,
  defaultLanguage = "TH",
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(defaultLanguage);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};
